In [3]:
import pandas as pd
import numpy as np
from pathlib import Path

In [6]:
fp = Path('data') / 'nypd-data.csv'
df = pd.read_csv(fp)
df

,unique_mos_id,first_name,last_name,command_now,shield_no,complaint_id,month_received,year_received,month_closed,year_closed,...,mos_age_incident,complainant_ethnicity,complainant_gender,complainant_age_incident,fado_type,allegation,precinct,contact_reason,outcome_description,board_disposition
0,10004,Jonathan,Ruiz,078 PCT,8409,42835,7,2019,5,2020,...,32,Black,Female,38.0,Abuse of Authority,Failure to provide RTKA card,78.0,Report-domestic dispute,No arrest made or summons issued,Substantiated (Command Lvl Instructions)
1,10007,John,Sears,078 PCT,5952,24601,11,2011,8,2012,...,24,Black,Male,26.0,Discourtesy,Action,67.0,Moving violation,Moving violation summons issued,Substantiated (Charges)
2,10007,John,Sears,078 PCT,5952,24601,11,2011,8,2012,...,24,Black,Male,26.0,Offensive Language,Race,67.0,Moving violation,Moving violation summons issued,Substantiated (Charges)
3,10007,John,Sears,078 PCT,5952,26146,7,2012,9,2013,...,25,Black,Male,45.0,Abuse of Authority,Question,67.0,PD suspected C/V of violation/crime - street,No arrest made or summons issued,Substantiated (Charges)
4,10009,Noemi,Sierra,078 PCT,24058,40253,8,2018,2,2019,...,39,NaN,NaN,16.0,Force,Physical force,67.0,Report-dispute,Arrest - other violation/crime,Substantiated (Command Discipline A)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33353,9992,Tomasz,Pulawski,078 PCT,2642,35671,8,2016,2,2017,...,36,Asian,Male,21.0,Discourtesy,Word,66.0,Moving violation,Moving violation summons issued,Unsubstantiated
33354,9992,Tomasz,Pulawski,078 PCT,2642,35671,8,2016,2,2017,...,36,Asian,Male,21.0,Abuse of Authority,Interference with recording,66.0,Moving violation,Moving violation summons issued,Unsubstantiated
33355,9992,Tomasz,Pulawski,078 PCT,2642,35671,8,2016,2,2017,...,36,Asian,Male,21.0,Abuse of Authority,Search (of person),66.0,Moving violation,Moving violation summons issued,Substantiated (Formalized Training)
33356,9992,Tomasz,Pulawski,078 PCT,2642,35671,8,2016,2,2017,...,36,Asian,Male,21.0,Abuse of Authority,Vehicle search,66.0,Moving violation,Moving violation summons issued,Substantiated (Formalized Training)
33357,9992,Tomasz,Pulawski,078 PCT,2642,35671,8,2016,2,2017,...,36,Asian,Male,21.0,Abuse of Authority,Frisk,66.0,Moving violation,Moving violation summons issued,Substantiated (Formalized Training)

In [9]:
df.groupby(['complainant_ethnicity', 'fado_type']).size()

complainant_ethnicity  fado_type
American Indian        Abuse of Authority       48
                       Discourtesy               8
                       Force                     7
                       Offensive Language        1
Asian                  Abuse of Authority      330
                       Discourtesy              86
                       Force                    96
                       Offensive Language       20
Black                  Abuse of Authority    10359
                       Discourtesy            2290
                       Force                  4072
                       Offensive Language      393
Hispanic               Abuse of Authority     3676
                       Discourtesy            1026
                       Force                  1596
                       Offensive Language      126
Other Race             Abuse of Authority      390
                       Discourtesy             124
                       Force                   142
                       Offensive Language       21
Refused                Abuse of Authority      173
                       Discourtesy              41
                       Force                    39
                       Offensive Language        6
Unknown                Abuse of Authority      580
                       Discourtesy             158
                       Force                   286
                       Offensive Language       17
White                  Abuse of Authority     1677
                       Discourtesy             487
                       Force                   553
                       Offensive Language       66
dtype: int64

In [18]:
df['full_name'] = df['first_name'] + ' ' + df['last_name']
officer_shields = df.groupby('shield_no').size().sort_values(ascending=False)
officer_names = df.groupby('full_name').size().sort_values(ascending=False)
officer_names.head(10)

full_name
Daniel Sbarra           75
Mathew Reich            75
Gary Messina            73
Joseph Tallarine        73
Christophe Mccormack    72
William Taylor          65
David Cheesewright      63
Paul Mcmahon            56
Mike Civil              56
Michael Raso            50
dtype: int64

In [20]:
shield_zero = df[df['shield_no'] == 0]
shield_zero

,unique_mos_id,first_name,last_name,command_now,shield_no,complaint_id,month_received,year_received,month_closed,year_closed,...,complainant_ethnicity,complainant_gender,complainant_age_incident,fado_type,allegation,precinct,contact_reason,outcome_description,board_disposition,full_name
214,10134,James,Hart,079 PCT,0,24367,10,2011,8,2012,...,Hispanic,Male,32.0,Force,Physical force,1.0,PD suspected C/V of violation/crime - street,No arrest made or summons issued,Unsubstantiated,James Hart
215,10134,James,Hart,079 PCT,0,24367,10,2011,8,2012,...,Hispanic,Male,32.0,Force,Pepper spray,1.0,PD suspected C/V of violation/crime - street,No arrest made or summons issued,Exonerated,James Hart
216,10134,James,Hart,079 PCT,0,26826,10,2012,3,2013,...,Black,Male,52.0,Offensive Language,Race,1.0,Other,Summons - other violation/crime,Unsubstantiated,James Hart
217,10134,James,Hart,079 PCT,0,26826,10,2012,3,2013,...,Black,Male,52.0,Discourtesy,Word,1.0,Other,Summons - other violation/crime,Unsubstantiated,James Hart
218,10134,James,Hart,079 PCT,0,32585,4,2015,10,2015,...,Black,Male,44.0,Force,Physical force,1.0,PD suspected C/V of violation/crime - street,Arrest - other violation/crime,Substantiated (Charges),James Hart
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33334,9965,Colbert,Martin,078 PCT,0,9018,3,2005,11,2005,...,Hispanic,Male,25.0,Abuse of Authority,Question and/or stop,90.0,PD suspected C/V of violation/crime - bldg,Arrest - resisting arrest,Exonerated,Colbert Martin
33335,9965,Colbert,Martin,078 PCT,0,39785,6,2018,1,2019,...,Hispanic,Female,32.0,Abuse of Authority,Refusal to process civilian complaint,78.0,Report-dispute,No arrest made or summons issued,Substantiated (Command Discipline A),Colbert Martin
33342,9979,Novaidul,Neon,078 PCT,0,29855,1,2014,9,2014,...,White,Male,72.0,Force,Gun Pointed,94.0,PD suspected C/V of violation/crime - street,Arrest - other violation/crime,Unsubstantiated,Novaidul Neon
33343,9979,Novaidul,Neon,078 PCT,0,36320,12,2016,5,2017,...,White,Male,35.0,Abuse of Authority,Threat of force (verbal or physical),94.0,EDP aided case,No arrest made or summons issued,Exonerated,Novaidul Neon
33344,9979,Novaidul,Neon,078 PCT,0,36320,12,2016,5,2017,...,White,Male,35.0,Abuse of Authority,Other,94.0,EDP aided case,No arrest made or summons issued,Substantiated (Formalized Training),Novaidul Neon